# Generated by Django 2.2.5 on 2019-10-15 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgname', models.CharField(max_length=200)),
                ('orgdesc', models.TextField(max_length=200)),
                ('orgid', models.AutoField(primary_key=True, serialize=False)),
                ('orgusername', models.CharField(max_length=200)),
                ('orgpw', models.CharField(default='', max_length=30)),
                ('orgstat', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'In-review')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectname', models.CharField(max_length=200, verbose_name='Project Name')),
                ('projdesc', models.CharField(max_length=500, verbose_name='Project Description')),
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projstatus', models.BooleanField(default=False, verbose_name='Project Status')),
                ('project_deadline', models.DateTimeField()),
                ('proj_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=128)),
                ('task_description', models.TextField(max_length=256)),
                ('task_priority', models.PositiveIntegerField(choices=[(1, 'Low Priority'), (2, 'Medium Priority'), (3, 'High Priority')], default=1)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_manager.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None, max_length=30, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
