# Generated by Django 2.2.5 on 2019-10-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_manager.Task'),
        ),
    ]
